In [59]:
import pandas as pd

In [153]:
file = "dataset.xlsx"
df_ind = pd.read_excel(file, sheet_name="Hoja1")
df_dep = pd.read_excel(file, sheet_name="Descenlaces")

df_ind = df_ind.head(40)

ind_vars = [
    "EDAD",
    "tipo CP",
    "DIA HOSP AL DG",
    "cirugia previa",
    "diálisis",
    "Falla renal",
    "Inmunosupresion",
    "Hosp previa 6m",
    "AKI CON HD durante tto",
    "No Apropiado",
    "Tto apropiado N°1",
    "Tto apropiado N°1 >24hrs",
    "Tto apropiado >48 hrs",
    "Monoterapia 1- cual",
    "combinado A- cual",
    "combinado B-cual",
    "Monoterapia 2- cual",
    "combinado A- cual2",
    "combinado B-cual2",
]

dep_vars = [
    "falla clinica",
    "Shock septico durante tto",
    "Falla renal nueva con diálisis",
    "MORTALIDAD 30 DIAS",
    "MORTALIDAD IIH"
]

In [154]:
df_ind = df_ind[ind_vars]
df_dep = df_dep[dep_vars]

df = pd.concat([df_ind, df_dep], axis=1)

In [156]:
df[df.isna().any(axis=1)]["Monoterapia 1- cual"]

14    Ceftazidima/avibactam
30                      NaN
Name: Monoterapia 1- cual, dtype: object

In [145]:
df = df.dropna(how="any")
df = df[df["DIA HOSP AL DG"] != "post mortem"]
df["DIA HOSP AL DG"] = df["DIA HOSP AL DG"].astype(int)

In [79]:
for c in df.columns:
    try:
        df[[c]] = df[[c]].apply(lambda col: col.str.lower() if col.dtype == 'object' else col)

    except:
        print("problems with column:", c)

In [80]:
def map_categories(value):
    if 'ceftazidima' in value or 'avi' in value:
        return 'C/A'
    elif value == 'no':
        return 'no'
    else:
        return 'otro'

In [81]:
for c in df.columns[13:-5]:
    df[c] = df[c].apply(map_categories)

In [82]:
df[ind_vars[:13]].head()

,EDAD,tipo CP,DIA HOSP AL DG,cirugia previa,diálisis,Falla renal,Inmunosupresion,Hosp previa 6m,AKI CON HD durante tto,No Apropiado,Tto apropiado N°1,Tto apropiado N°1 >24hrs,Tto apropiado >48 hrs
0,34.0,ndm,24,si,no,no,no,no,no,2.0,1.0,si,no
1,36.0,kpc,18,no,no,no,si,si,no,2.0,1.0,no,no
2,80.0,ndm,66,si,no,no,no,no,no,1.0,2.0,no,no
3,74.0,kpc,78,si,no,no,no,no,no,2.0,1.0,no,si
4,55.0,kpc,23,no,no,no,si,no,no,2.0,1.0,no,si

In [83]:
df = df.drop(['tipo CP', 'No Apropiado', 'Tto apropiado N°1'], axis=1)

In [84]:
df[df.columns[2:10]]

,cirugia previa,diálisis,Falla renal,Inmunosupresion,Hosp previa 6m,AKI CON HD durante tto,Tto apropiado N°1 >24hrs,Tto apropiado >48 hrs
0,si,no,no,no,no,no,si,no
1,no,no,no,si,si,no,no,no
2,si,no,no,no,no,no,no,no
3,si,no,no,no,no,no,no,si
4,no,no,no,si,no,no,no,si
5,no,no,no,no,no,no,no,si
6,si,no,si,si,no,no,no,si
7,no,no,si,no,no,no,no,si
8,si,no,no,no,no,no,no,si
9,si,no,no,no,no,no,no,no
10,no,no,no,no,si,no,no,si
11,si,no,no,no,no,no,no,si
12,no,no,no,si,si,no,no,si
13,si,no,si,no,no,no,no,si
15,no,no,no,si,si,no,no,si
16,no,no,no,si,si,no,no,no
17,si,no,no,si,si,no,no,no
18,no,no,si,si,no,no,no,si
19,no,no,no,si,no,si,no,no
20,si,si,si,no,si,no,no,no
21,si,si,si,no,no,no,no,si
22,si,no,si,si,si,no,no,si
23,si,no,si,si,si,no,no,si
24,si,no,no,no,no,no,no,si
25,no,no,no,si,no,no,no,si
26,no,no,si,no,no,no,no,si
27,si,si,si,no,no,no,no,si
28,si,no,no,si,si,no,no,si
31,si,si,si,no,si,no,no,no
32,si,si,si,no,no,no,no,si
33,si,si,si,si,si,no,no,no
34,si,no,no,si,no,no,no,no
35,si,si,no,si,no,no,no,si
36,si,no,si,no,no,no,no,si
37,si,si,si,si,no,si,no,no
38,si,no,no,no,no,no,si,no
39,no,no,no,no,no,no,si,no

In [85]:
df[df.columns[-5:]]

,falla clinica,Shock septico durante tto,Falla renal nueva con diálisis,MORTALIDAD 30 DIAS,MORTALIDAD IIH
0,no,no,no,no,no
1,no,no,no,no,no
2,no,no,no,no,no
3,no,no,no,no,no
4,no,no,no,no,no
5,no,no,no,no,no
6,no,no,no,no,no
7,no,no,no,no,no
8,no,no,no,no,no
9,no,si,no,no,no
10,no,no,no,no,no
11,no,si,no,no,no
12,si,si,no,no,no
13,si,si,no,no,no
15,no,no,no,si,si
16,no,si,no,si,si
17,no,si,no,si,si
18,no,si,no,si,si
19,si,no,no,si,no
20,si,no,no,si,no
21,si,si,si,si,si
22,si,si,no,si,si
23,si,si,no,si,si
24,si,si,no,si,si
25,si,si,no,si,si
26,si,no,no,si,si
27,si,si,si,si,si
28,si,si,no,si,si
31,si,si,no,si,si
32,si,si,no,si,si
33,si,no,no,si,si
34,si,si,no,si,si
35,si,si,no,si,si
36,si,no,no,si,si
37,si,si,no,si,si
38,si,si,no,si,si
39,si,si,si,si,si

In [86]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

for c in df.columns[-5:]:
    df[c] = label_encoder.fit_transform(df[c])

for c in df.columns[2:10]:
    df[c] = label_encoder.fit_transform(df[c])

In [88]:
for name in ["EDAD", "DIA HOSP AL DG"]:
    df[name] = df[name]/df[name].max()

df.head()

,EDAD,DIA HOSP AL DG,cirugia previa,diálisis,Falla renal,Inmunosupresion,Hosp previa 6m,AKI CON HD durante tto,Tto apropiado N°1 >24hrs,Tto apropiado >48 hrs,...,combinado A- cual,combinado B-cual,Monoterapia 2- cual,combinado A- cual2,combinado B-cual2,falla clinica,Shock septico durante tto,Falla renal nueva con diálisis,MORTALIDAD 30 DIAS,MORTALIDAD IIH
0,0.4250,0.15000,1,0,0,0,0,0,1,0,...,otro,otro,no,otro,C/A,0,0,0,0,0
1,0.4500,0.11250,0,0,0,1,1,0,0,0,...,otro,otro,otro,no,no,0,0,0,0,0
2,1.0000,0.41250,1,0,0,0,0,0,0,0,...,no,no,no,no,no,0,0,0,0,0
3,0.9250,0.48750,1,0,0,0,0,0,0,1,...,otro,otro,no,no,no,0,0,0,0,0
4,0.6875,0.14375,0,0,0,1,0,0,0,1,...,otro,otro,C/A,no,no,0,0,0,0,0

In [127]:
df[df.columns[10:16]]

,Monoterapia 1- cual,combinado A- cual,combinado B-cual,Monoterapia 2- cual,combinado A- cual2,combinado B-cual2
0,no,otro,otro,no,otro,C/A
1,no,otro,otro,otro,no,no
2,no,no,no,no,no,no
3,no,otro,otro,no,no,no
4,no,otro,otro,C/A,no,no
5,no,otro,otro,no,no,no
6,no,otro,otro,C/A,no,no
7,no,otro,otro,no,no,no
8,C/A,no,no,no,no,no
9,no,otro,otro,C/A,no,no
10,no,otro,otro,C/A,no,no
11,no,otro,otro,no,no,no
12,C/A,no,no,otro,no,no
13,C/A,no,no,no,no,no
15,C/A,no,no,no,no,no
16,no,C/A,otro,no,no,no
17,otro,no,no,C/A,no,no
18,C/A,no,no,no,C/A,otro
19,no,no,no,no,no,no
20,no,otro,otro,no,no,no
21,no,otro,otro,no,no,no
22,otro,no,no,otro,no,no
23,C/A,no,no,otro,no,no
24,C/A,otro,no,no,no,no
25,C/A,no,no,otro,no,no
26,C/A,no,no,no,no,no
27,C/A,no,no,no,no,no
28,C/A,no,no,no,no,no
31,no,no,no,no,no,no
32,C/A,no,no,no,no,no
33,otro,no,no,no,C/A,otro
34,otro,no,no,no,no,no
35,C/A,no,no,no,no,no
36,C/A,no,no,no,no,no
37,no,no,no,no,no,no
38,otro,no,no,no,no,no
39,C/A,no,no,otro,no,no

In [130]:
df_ca = pd.DataFrame()
df_ca['medicamento'] = df[df.columns[11:16]].apply(lambda row: ' '.join(row.values.astype(str)), axis=1)
df_ca['resumen'] = df_ca["medicamento"].apply(
    lambda x: 'C/A' if 'C/A' in x else ('otro' if 'otro' in x else 'no')
)

df_ca

              medicamento resumen
0   otro otro no otro C/A     C/A
1    otro otro otro no no    otro
2          no no no no no      no
3      otro otro no no no    otro
4     otro otro C/A no no     C/A
5      otro otro no no no    otro
6     otro otro C/A no no     C/A
7      otro otro no no no    otro
8          no no no no no      no
9     otro otro C/A no no     C/A
10    otro otro C/A no no     C/A
11     otro otro no no no    otro
12       no no otro no no    otro
13         no no no no no      no
15         no no no no no      no
16      C/A otro no no no     C/A
17        no no C/A no no     C/A
18      no no no C/A otro     C/A
19         no no no no no      no
20     otro otro no no no    otro
21     otro otro no no no    otro
22       no no otro no no    otro
23       no no otro no no    otro
24       otro no no no no    otro
25       no no otro no no    otro
26         no no no no no      no
27         no no no no no      no
28         no no no no no      no
31         no no no no no      no
32         no no no no no      no
33      no no no C/A otro     C/A
34         no no no no no      no
35         no no no no no      no
36         no no no no no      no
37         no no no no no      no
38         no no no no no      no
39       no no otro no no    otro

In [132]:
dummies = pd.get_dummies(df_ca["resumen"]).astype(int)

In [93]:
DFS = []
for c in df.columns[10:16]:
    df_ = pd.get_dummies(df[c], prefix=c).astype(int)
    DFS.append(df_)

dummies = pd.concat(DFS, axis=1)
dummies

,Monoterapia 1- cual_C/A,Monoterapia 1- cual_no,Monoterapia 1- cual_otro,combinado A- cual_C/A,combinado A- cual_no,combinado A- cual_otro,combinado B-cual_no,combinado B-cual_otro,Monoterapia 2- cual_C/A,Monoterapia 2- cual_no,Monoterapia 2- cual_otro,combinado A- cual2_C/A,combinado A- cual2_no,combinado A- cual2_otro,combinado B-cual2_C/A,combinado B-cual2_no,combinado B-cual2_otro
0,0,1,0,0,0,1,0,1,0,1,0,0,0,1,1,0,0
1,0,1,0,0,0,1,0,1,0,0,1,0,1,0,0,1,0
2,0,1,0,0,1,0,1,0,0,1,0,0,1,0,0,1,0
3,0,1,0,0,0,1,0,1,0,1,0,0,1,0,0,1,0
4,0,1,0,0,0,1,0,1,1,0,0,0,1,0,0,1,0
5,0,1,0,0,0,1,0,1,0,1,0,0,1,0,0,1,0
6,0,1,0,0,0,1,0,1,1,0,0,0,1,0,0,1,0
7,0,1,0,0,0,1,0,1,0,1,0,0,1,0,0,1,0
8,1,0,0,0,1,0,1,0,0,1,0,0,1,0,0,1,0
9,0,1,0,0,0,1,0,1,1,0,0,0,1,0,0,1,0
10,0,1,0,0,0,1,0,1,1,0,0,0,1,0,0,1,0
11,0,1,0,0,0,1,0,1,0,1,0,0,1,0,0,1,0
12,1,0,0,0,1,0,1,0,0,0,1,0,1,0,0,1,0
13,1,0,0,0,1,0,1,0,0,1,0,0,1,0,0,1,0
15,1,0,0,0,1,0,1,0,0,1,0,0,1,0,0,1,0
16,0,1,0,1,0,0,0,1,0,1,0,0,1,0,0,1,0
17,0,0,1,0,1,0,1,0,1,0,0,0,1,0,0,1,0
18,1,0,0,0,1,0,1,0,0,1,0,1,0,0,0,0,1
19,0,1,0,0,1,0,1,0,0,1,0,0,1,0,0,1,0
20,0,1,0,0,0,1,0,1,0,1,0,0,1,0,0,1,0
21,0,1,0,0,0,1,0,1,0,1,0,0,1,0,0,1,0
22,0,0,1,0,1,0,1,0,0,0,1,0,1,0,0,1,0
23,1,0,0,0,1,0,1,0,0,0,1,0,1,0,0,1,0
24,1,0,0,0,0,1,1,0,0,1,0,0,1,0,0,1,0
25,1,0,0,0,1,0,1,0,0,0,1,0,1,0,0,1,0
26,1,0,0,0,1,0,1,0,0,1,0,0,1,0,0,1,0
27,1,0,0,0,1,0,1,0,0,1,0,0,1,0,0,1,0
28,1,0,0,0,1,0,1,0,0,1,0,0,1,0,0,1,0
31,0,1,0,0,1,0,1,0,0,1,0,0,1,0,0,1,0
32,1,0,0,0,1,0,1,0,0,1,0,0,1,0,0,1,0
33,0,0,1,0,1,0,1,0,0,1,0,1,0,0,0,0,1
34,0,0,1,0,1,0,1,0,0,1,0,0,1,0,0,1,0
35,1,0,0,0,1,0,1,0,0,1,0,0,1,0,0,1,0
36,1,0,0,0,1,0,1,0,0,1,0,0,1,0,0,1,0
37,0,1,0,0,1,0,1,0,0,1,0,0,1,0,0,1,0
38,0,0,1,0,1,0,1,0,0,1,0,0,1,0,0,1,0
39,1,0,0,0,1,0,1,0,0,0,1,0,1,0,0,1,0

In [133]:
objetive = dep_vars[0]

y = df[objetive]
X = pd.concat([df[df.columns[:10]], dummies], axis=1)
X.head()

,EDAD,DIA HOSP AL DG,cirugia previa,diálisis,Falla renal,Inmunosupresion,Hosp previa 6m,AKI CON HD durante tto,Tto apropiado N°1 >24hrs,Tto apropiado >48 hrs,C/A,no,otro
0,0.4250,0.15000,1,0,0,0,0,0,1,0,1,0,0
1,0.4500,0.11250,0,0,0,1,1,0,0,0,0,0,1
2,1.0000,0.41250,1,0,0,0,0,0,0,0,0,1,0
3,0.9250,0.48750,1,0,0,0,0,0,0,1,0,0,1
4,0.6875,0.14375,0,0,0,1,0,0,0,1,1,0,0

In [134]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 1. Dividir el dataset en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# 2. Crear y ajustar el modelo de regresión logística
model = LogisticRegression(solver='liblinear')  # 'liblinear' funciona bien con datasets pequeños
model.fit(X_train, y_train)

# 3. Hacer predicciones sobre los datos de prueba
y_pred = model.predict(X_test)

# 4. Evaluar el rendimiento del modelo
# Calcular la precisión
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.4f}')

# Generar la matriz de confusión
conf_matrix = confusion_matrix(y_test, y_pred)
print('Confusion Matrix:')
print(conf_matrix)

# Generar un reporte de clasificación
class_report = classification_report(y_test, y_pred)
print('Classification Report:')
print(class_report)

# 5. Interpretar los coeficientes del modelo
coefficients = model.coef_[0]
importance_df = pd.DataFrame({
    'Feature': X_train.columns,
    'Coefficient': coefficients
}).sort_values(by='Coefficient', ascending=False)

Accuracy: 1.0000
Confusion Matrix:
[[4 0]
 [0 4]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         4
           1       1.00      1.00      1.00         4

    accuracy                           1.00         8
   macro avg       1.00      1.00      1.00         8
weighted avg       1.00      1.00      1.00         8

In [135]:
print('Feature Importances (Coefficients):')
importance_df

Feature Importances (Coefficients):

                     Feature  Coefficient
3                   diálisis     0.929160
4                Falla renal     0.674519
11                        no     0.625200
8   Tto apropiado N°1 >24hrs     0.436942
7     AKI CON HD durante tto     0.384378
2             cirugia previa     0.370423
12                      otro     0.304582
5            Inmunosupresion     0.301271
6             Hosp previa 6m     0.216818
9      Tto apropiado >48 hrs    -0.059138
1             DIA HOSP AL DG    -0.185197
0                       EDAD    -0.583620
10                       C/A    -1.096344

In [141]:
import numpy as np

coef = importance_df[importance_df["Feature"]=="C/A"]["Coefficient"].values[0]

# Calcula el Odds Ratio
odds_ratio_C_A = np.exp(coef)

In [142]:
odds_ratio_C_A

0.33409016726432667

In [125]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 1. Dividir el dataset en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 2. Crear y ajustar el modelo de Random Forest
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# 3. Hacer predicciones sobre los datos de prueba
y_pred = model.predict(X_test)

# 4. Evaluar el rendimiento del modelo
# Calcular la precisión
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.4f}')

# Generar la matriz de confusión
conf_matrix = confusion_matrix(y_test, y_pred)
print('Confusion Matrix:')
print(conf_matrix)

# Generar un reporte de clasificación
class_report = classification_report(y_test, y_pred)
print('Classification Report:')
print(class_report)

# 5. Obtener la importancia de las características
importances = model.feature_importances_
importance_df = pd.DataFrame({
    'Feature': X_train.columns,
    'Importance': importances
}).sort_values(by='Importance', ascending=False)

Accuracy: 0.7500
Confusion Matrix:
[[2 1]
 [1 4]]
Classification Report:
              precision    recall  f1-score   support

           0       0.67      0.67      0.67         3
           1       0.80      0.80      0.80         5

    accuracy                           0.75         8
   macro avg       0.73      0.73      0.73         8
weighted avg       0.75      0.75      0.75         8

In [126]:
print('Feature Importances:')
importance_df

Feature Importances:

                     Feature  Importance
0                       EDAD    0.146629
1             DIA HOSP AL DG    0.111216
16       combinado B-cual_no    0.097665
3                   diálisis    0.082487
4                Falla renal    0.079183
17     combinado B-cual_otro    0.077953
14      combinado A- cual_no    0.049517
11    Monoterapia 1- cual_no    0.040582
2             cirugia previa    0.036661
15    combinado A- cual_otro    0.035621
19    Monoterapia 2- cual_no    0.030882
20  Monoterapia 2- cual_otro    0.029016
10   Monoterapia 1- cual_C/A    0.028537
6             Hosp previa 6m    0.027655
5            Inmunosupresion    0.027000
18   Monoterapia 2- cual_C/A    0.026700
9      Tto apropiado >48 hrs    0.021523
7     AKI CON HD durante tto    0.017993
12  Monoterapia 1- cual_otro    0.008120
23   combinado A- cual2_otro    0.007410
13     combinado A- cual_C/A    0.005339
24     combinado B-cual2_C/A    0.004202
22     combinado A- cual2_no    0.003726
25      combinado B-cual2_no    0.002068
8   Tto apropiado N°1 >24hrs    0.001716
26    combinado B-cual2_otro    0.000597
21    combinado A- cual2_C/A    0.000000